# platform :ios, '9.0'

target 'ICU996' do
  use_frameworks!
  
  pod 'SnapKit', '~> 4.2.0'
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SDWebImage', '~> 4.4.6'

  target 'ICU996Tests' do
    inherit! :search_paths
  end

end
