platform :ios, '10.0'
inhibit_all_warnings!

def basic_component
  # 基础组件
  pod 'SnapKit', '~> 4.2.0'
  pod 'Alamofire', '~> 4.7.3'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SDWebImage', '~> 4.4.6'
  pod 'SwiftyUserDefaults', '4.0.0-beta.2'
  pod 'DeviceKit', '~> 1.3'
end

def ui_component
  # UI 组件
  pod 'pop', '~> 1.0.12'
#  pod 'AppCenter'
end

def buz_component
  # 业务组件
  # pod ''
end

def debug_component
  pod 'Reveal-SDK', :path => 'Reveal', :configurations => ['Debug']
  pod 'FLEX', '~> 2.0', :configurations => ['Debug']
end

target 'ICU996' do
  use_frameworks!

  basic_component
  ui_component
  buz_component
  
  debug_component

  target 'ICU996Tests' do
    inherit! :search_paths
  end
end
